### PR TITLE
Add support to PHP 8

### PR DESCRIPTION
**Pull request by f-liva**

### CODE REVIEW

**Comment by pdawson** [comment]
👏🏻

**Comment by ronappleton** [comment]
👏

**Comment by ronappleton** [comment]
@albertcht Can we have this merged please, would be nice to stop ignoring platform requirements lol

**Comment by boboldehampsink** [comment]
+1

**Comment by peterjaap** [comment]
@albertcht can you merge this?

**Comment by vdvcoder** [comment]
ping pong! merge please.

**Comment by vdvcoder** [comment]
😩

**Comment by brino** [comment]
bump!

**Comment by ronappleton** [comment]
@albertcht Thank you so much 👍

**Pull request merged**
