### PR TITLE
Laravel 8.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 8.x.

**Before merging**, you need to:

- Checkout the `l8-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^9.3`. If you would like to also upgrade your tests, you may run the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/invisible-recaptcha.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "albertcht/invisible-recaptcha": "dev-l8-compatibility",
    }
}
```

Finally, run: `composer update`

**Review by rickmills — APPROVED** [review]
All working ok, any chance you can get this merged and tagged when you have a couple of minutes to spare @albertcht

**Comment by voicecode-bv** [comment]
@albertcht Can you please merge and tag this? :) Thanks!

**Comment by williamnwogbo** [comment]
Can this be merged !

**Comment by pjebs** [comment]
@albertcht Can this be merged?

**Comment by ErPrateekSingh** [comment]
@albertcht Can this be merged?

**Comment by pjebs** [comment]
I actually gave up on this library after realising that it's actually trivial to implement recaptca without the assistance of any library.

**Comment by garbinmarcelo** [comment]
> I actually gave up on this library after realising that it's actually trivial to implement recaptca without the assistance of any library.

Could you give an example or link about it? Thanks

**Comment by voicecode-bv** [comment]
> > I actually gave up on this library after realising that it's actually trivial to implement recaptca without the assistance of any library.
> 
> Could you give an example or link about it? Thanks

Here you go:

https://gist.github.com/JeffreyWay/b0dcc5975a3ca9a51493f282ed0966c2

Don’t forget to do a serverside check during your post request.

**Comment by garbinmarcelo** [comment]
> Here you go:
> 
> https://gist.github.com/JeffreyWay/b0dcc5975a3ca9a51493f282ed0966c2
> 
> Don’t forget to do a serverside check during your post request.

Thanks for the quick return. I will check this solution.

**Comment by muarachmann** [comment]
Can this be merged? thanks

**Comment by khaizbt** [comment]
tested, and running normally,Can this be merged !

**Comment by albertcht** [comment]
Hi all,

Sorry for the long wait, and I've merged this pull request.

**Pull request merged**
