### PR TITLE
Add support for Laravel 7

### PR DESCRIPTION
**Pull request by hedii**
Close https://github.com/albertcht/invisible-recaptcha/issues/122

### CODE REVIEW

**Comment by PIPONCHOV** [comment]
Please merge it to master. Thanks in advance!

**Comment by atthakorn** [comment]
Hello @albertcht     

Please review this PR and merge this.

Thank you.

**Comment by poseso** [comment]
Hope this can be merged soon

**Comment by mydnic** [comment]
Any news ? @albertcht

**Comment by albertcht** [comment]
Sorry for the late reply, I've merged this pull request and released a new version.

**Pull request merged**
