### PR TITLE
Patch for Internet Explorer not supporting .closest method

### PR DESCRIPTION
**Pull request by leopado**
Hello,
I noticed that this plugin doesn't work on Internet Explorer because it does not support the closest method you're using to find the nearest form to the #g-recaptcha element.
I have added some codes to patch and make it working also on IE (I've found the solution here https://developer.mozilla.org/it/docs/Web/API/Element/closest).

Best Regards.

Leonardo.

### CODE REVIEW

**Comment by albertcht** [comment]
Hi @leopado, thanks a lot for your pr. May I ask what your IE version is? Because since v1.5, I have included polyfill.js to fix this issue, it should not happen. I tested it with IE 11, it worked fine.

**Comment by leopado** [comment]
Hi @albertcht,
I've tested on microsoft Edge e and IE 11.1715 but polyfill had not fixed this issue for me and my customers.

**Comment by albertcht** [comment]
hi @leopado , thanks for your report. I will test it with other different IE versions again.

**Comment by albertcht** [comment]
@leopado , I also use this package in my personal website, and I tested it via https://www.browserling.com/internet-explorer-testing to see if the contact form triggers the 
captcha validation. As the result, it worked properly on any IE version including Edge. 
(You can check with my website: albert-chen.com on this platform again)
So basically I cannot reproduce this issue. Having no clues at this moment yet, if you have any other ideas to reproduce this issue, welcome to comment below. I will keep this PR open for a while. Thank you so much!

**Pull request closed without merging**
