### PR TITLE
Add multiple forms feature

### PR DESCRIPTION
**Pull request by QuentinBontemps**

### CODE REVIEW

**Comment by marcelogarbin** [comment]
Is this working in the master branch?

**Comment by QuentinBontemps** [comment]
Yes, I have multiple forms in the same page. 
But my pull request isn't merge yet.

**Comment by marcelogarbin** [comment]
Ok, I'll be waiting for this to happen.. it looks like this is stopped..

**Comment by albertcht** [comment]
Hi @QuentinBontemps ,

Sorry for the late response. Because there's the other `multi-form` branch for this purpose, I still decide to make them separate branches.

**Pull request closed without merging**
