### PR TITLE
pass the form through the _submitEvent function

### PR DESCRIPTION
**Pull request by mroedel**
that ensures the ability of additional querying (e.g. when you have more than one form on a page)

### CODE REVIEW

**Comment by albertcht** [comment]
hi @mroedel , thanks for your pull request. I was just wondering what's the purpose to pass `_captchaForm` to `_submitEvent` since you can get `_captchaForm` element everywhere in your js code?

**Comment by mroedel** [comment]
that's right, but how you difference more than one ajax form on a single page?

**Comment by albertcht** [comment]
Hi @mroedel , sorry for the late reply. This branch is only for one captcha in a single page. There's the other `multi-forms` branch for multiple captcha purpose.
https://github.com/albertcht/invisible-recaptcha/tree/multi-forms

**Comment by albertcht** [comment]
You can directly listen the captcha event for more elegant usage on that branch, for example:
```javascript
$('#form_1').on('captcha', function(e) {
    // set it as false if your don't want to submit your from directly
    _submitAction = false;
    // do your ajax action or other stuff here
});
```

**Pull request closed without merging**
